DROP TABLE IF EXISTS utenti;
DROP TABLE IF EXISTS corsi;

CREATE TABLE corsi (
    idcorso INTEGER PRIMARY KEY AUTOINCREMENT,
    nome VARCHAR(50) UNIQUE NOT NULL,
    descrizione TEXT NOT NULL
);

CREATE TABLE utenti (
    idutente INTEGER PRIMARY KEY AUTOINCREMENT,
    ruolo INTEGER NOT NULL,
    username VARCHAR(30) UNIQUE NOT NULL,
    password VARCHAR(20) NOT NULL
);